### ISSUE TITLE
arm-none-eabi-g++

### ISSUE THREAD

**Issue by markd666** [hexdae/bazel-arm-none-eabi#9]
Is there a simple way to specify compiling with arm-none-eabi-g++ instead of arm-none-eabi-gcc??

Have a bug with my code C++ code and how it is linked. Want to cross off the possibility that the compiler is the issue.

Thanks in advance.
Mark

**Comment by Drew3164** [comment]
Did you ever get this fixed?

**Comment by hexdae** [comment]
I actually did not, sorry I did not see this comment, I'll make sure I try to fix it. @markd666 do you have a simple example I can use to reproduce issues?

**Comment by hexdae** [comment]
Also, do you mean `arm-none-eabi-c++` ?

**Comment by hexdae** [comment]
Ok, I have a PR to address this issue, I will merge it only if it is still relevant: #24

**Comment by RyanDraves** [comment]
I found it useful and would like it merged
